<?php

namespace Database\Seeders;

use App\Models\District;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Validator;
use Illuminate\Validation\Rules\Password;
use Illuminate\Validation\ValidationException;
use Spatie\Permission\Models\Role;

class DefaultRoleUserSeeder extends Seeder
{
    public function run(): void
    {
        $configuration = config('iomp.demo_users');
        $validator = Validator::make($configuration, [
            'staff_password' => ['required', 'string', Password::min(12)->mixedCase()->letters()->numbers()->symbols()],
            'investor_password' => ['required', 'string', Password::min(12)->mixedCase()->letters()->numbers()->symbols()],
            'investor_email_pattern' => ['required', 'string'],
            'roles' => ['required', 'array', 'size:6'],
            'roles.*.role' => ['required', 'string'],
            'roles.*.name' => ['required', 'string', 'max:255'],
            'roles.*.email' => ['required', 'email:rfc', 'distinct'],
            'roles.*.type' => ['required', 'in:staff,investor'],
        ]);

        if ($validator->fails()) {
            throw new ValidationException($validator);
        }

        $configuration = $validator->validated();
        $investor = collect($configuration['roles'])->firstWhere('role', 'Investor');
        if ($investor['email'] !== sprintf($configuration['investor_email_pattern'], 1)) {
            throw ValidationException::withMessages([
                'roles' => 'The default Investor email must be the first address generated by DEMO_INVESTOR_EMAIL_PATTERN.',
            ]);
        }

        foreach ($configuration['roles'] as $account) {
            $user = User::query()->firstOrNew(['email' => $account['email']]);

            if (! $user->exists) {
                $user->password = Hash::make($account['type'] === User::ACCOUNT_STAFF
                    ? $configuration['staff_password']
                    : $configuration['investor_password']);
            }

            $user->forceFill([
                'name' => $account['name'],
                'account_type' => $account['type'] === User::ACCOUNT_STAFF ? User::ACCOUNT_STAFF : User::ACCOUNT_INVESTOR,
                'status' => User::STATUS_ACTIVE,
                'email_verified_at' => $user->email_verified_at ?? now(),
            ])->save();

            $role = Role::findOrCreate($account['role'], 'web');
            $user->syncRoles([$role]);
        }

        $districtOfficerAccount = collect($configuration['roles'])->firstWhere('role', 'District Officer');
        $districtOfficer = User::query()->where('email', $districtOfficerAccount['email'])->firstOrFail();
        $district = District::query()->orderBy('id')->first();
        if ($district) {
            $districtOfficer->districtAssignments()->firstOrCreate(
                ['district_id' => $district->id, 'starts_at' => now()->startOfDay()],
                ['is_primary' => true],
            );
        }
    }
}
