<x-public-layout title="Investor user guide" description="A practical guide to discovering opportunities, managing your investment mandate, and completing secure onboarding with GIPA.">
    <section class="guide-hero">
        <div class="shell guide-hero__inner">
            <div><p class="eyebrow"><span></span> Investor guidance</p><h1>Invest with confidence across Ghana.</h1><p>Follow the complete journey from opportunity discovery to a reviewed investor profile.</p></div>
            <div class="guide-hero__meta"><strong>Investor guide</strong><span>Public reference</span><small>Updated {{ now()->format('F Y') }}</small></div>
        </div>
    </section>
    <div class="shell guide-layout">
        <nav class="guide-nav" aria-label="Guide sections">
            <strong>On this page</strong>
            <a href="#start">Getting started</a><a href="#discover">Discover projects</a><a href="#mandate">Investment mandate</a><a href="#inquiries">Express interest</a><a href="#onboarding">KYC onboarding</a><a href="#status">Track progress</a><a href="#assistant">GIPA Assistant</a><a href="#security">Security</a><a href="#help">Help</a>
        </nav>
        <article class="guide-document">
            <section class="guide-overview"><div><span>01</span><strong>Create an account</strong></div><div><span>02</span><strong>Set your mandate</strong></div><div><span>03</span><strong>Review matches</strong></div><div><span>04</span><strong>Complete KYC</strong></div></section>

            <section id="start" class="guide-section"><p class="guide-section__number">01 / Account access</p><h2>Getting started</h2><p>Create one investor account using an email address you control. Staff accounts use a separate, restricted entry point and are not created from public registration.</p><ol><li>Open <a href="{{ route('register') }}">Create investor account</a> and provide your identity and contact details.</li><li>Use the verification message sent to your email address.</li><li>Sign in at <a href="{{ route('login') }}">Investor login</a>. After verification, you will enter the secure investor workspace at <strong>/portal</strong>.</li></ol><div class="guide-note"><strong>Already signed in?</strong><span>Use the Workspace link in the public header to return to your dashboard.</span></div></section>

            <section id="discover" class="guide-section"><p class="guide-section__number">02 / Public discovery</p><h2>Find investment opportunities</h2><p>The public catalogue contains opportunities approved for publication. Search by project name, sector, district, or region, then open a project to review its summary, capital requirement, location, contacts, and supporting public information.</p><div class="guide-actions"><a class="button button--gold" href="{{ route('opportunities.index') }}">Browse opportunities</a><a class="button button--outline" href="{{ route('districts.index') }}#investment-map">Open investment map</a></div><ul><li>Use district profiles to compare readiness and the local project pipeline.</li><li>Treat map locations as discovery aids and rely on the published project record for official details.</li><li>Only published opportunities and districts appear in recommendations.</li></ul></section>

            <section id="mandate" class="guide-section"><p class="guide-section__number">03 / Personalisation</p><h2>Define your investment mandate</h2><p>In the investor workspace, choose preferred sectors and regions, a capital range and currency, and an optional minimum district-readiness score. Saving the form refreshes your recommendations.</p><div class="guide-grid"><article><strong>Sector alignment</strong><span>Projects in your preferred sectors receive the strongest score contribution.</span></article><article><strong>Geographic focus</strong><span>Preferred regions help prioritise relevant districts.</span></article><article><strong>Capital fit</strong><span>Amount and currency are compared with published financial requirements.</span></article><article><strong>Readiness</strong><span>An optional threshold limits projects by district readiness.</span></article></div><p>Each recommendation displays a score and plain-language reasons. The ranking is deterministic; it does not use hidden profiling or generative AI.</p></section>

            <section id="inquiries" class="guide-section"><p class="guide-section__number">04 / Engagement</p><h2>Express interest in a project</h2><ol><li>Open the selected opportunity and review its location, sector, financial requirement, contacts, and available files.</li><li>Complete the expression-of-interest form with accurate contact details and your message.</li><li>Submit once and retain the displayed inquiry reference for follow-up.</li></ol><div class="guide-note guide-note--warning"><strong>Before submitting</strong><span>Do not include passwords, bank credentials, or unnecessary identity documents in an inquiry.</span></div></section>

            <section id="onboarding" class="guide-section"><p class="guide-section__number">05 / Due diligence</p><h2>Complete secure KYC onboarding</h2><ol><li>Open <strong>KYC onboarding</strong> in your workspace and start an application.</li><li>Select the correct evidence type and upload the requested PDF, JPEG, or PNG file. The maximum file size is 10 MB.</li><li>Add issue or expiry dates where applicable.</li><li>Confirm that every required evidence type is present, then submit the case for staff review.</li></ol><p>Files are private and enter security quarantine. Only you and authorised GIPA reviewers can access them. A reviewer may accept evidence, request a replacement, approve the case, or reject it with a reason.</p></section>

            <section id="status" class="guide-section"><p class="guide-section__number">06 / Monitoring</p><h2>Track your application</h2><div class="guide-statuses"><div><strong>Draft</strong><span>You can add evidence and edit the submission.</span></div><div><strong>Submitted / under review</strong><span>GIPA is assessing the case; editing is temporarily closed.</span></div><div><strong>Action required</strong><span>Read the reviewer note, replace or add evidence, and resubmit.</span></div><div><strong>Approved / rejected</strong><span>The decision and timeline remain visible in your workspace.</span></div></div></section>

            <section id="assistant" class="guide-section"><p class="guide-section__number">07 / Guided answers</p><h2>Ask the GIPA Assistant</h2><p>The GIPA Assistant is a floating help button in the lower corner of every public page and your investor workspace. Open it to ask questions in plain language and get grounded answers with links to the source material.</p><ol><li>Select the pulsing assistant button to open the chat panel.</li><li>Type a question about investment opportunities, sectors, districts, regions, onboarding steps, or certificate verification.</li><li>Read the answer and follow the cited sources or suggested links for the official record.</li></ol><div class="guide-grid"><article><strong>Grounded responses</strong><span>Answers are drawn from GIPA's published knowledge base and live platform data, with citations you can verify.</span></article><article><strong>Live figures</strong><span>Questions such as how many opportunities or sectors are listed are answered from current platform counts.</span></article><article><strong>Certificate checks</strong><span>The assistant explains how to verify a certificate using its QR code or verification link rather than guessing a result.</span></article><article><strong>Safe by design</strong><span>The assistant declines when it has no verified source, ignores attempts to change its instructions, and never requests your password or KYC files.</span></article></div><div class="guide-note"><strong>Conversation memory</strong><span>Your chat stays within your current session so follow-up questions keep context. Do not paste passwords or identity documents into the chat.</span></div></section>

            <section id="security" class="guide-section"><p class="guide-section__number">08 / Account safety</p><h2>Protect your information</h2><ul><li>Use a unique password and never share verification or reset links.</li><li>Sign out when using a shared device.</li><li>Upload KYC files only through the secure investor workspace.</li><li>Check the opportunity and district records before acting on third-party messages.</li><li>Public pages never expose your KYC evidence, account history, or investment preferences.</li></ul></section>

            <section id="help" class="guide-section"><p class="guide-section__number">09 / Assistance</p><h2>Get help</h2><p>For access problems, include your registration email and a concise description of the issue. For an opportunity inquiry, include the project title and your inquiry reference. Never send passwords or full identity documents by email.</p><div class="guide-contact"><div><span>Investor access</span><a href="{{ route('login') }}">Open investor login</a></div><div><span>Opportunity support</span><a href="mailto:info@example.gov.gh">info@example.gov.gh</a></div></div></section>
        </article>
    </div>
</x-public-layout>
