<x-admin-layout title="Staff user guide">
    <header class="admin-page-heading"><div><p class="admin-kicker">Restricted operational guidance</p><h1>Staff user guide</h1><p>Role-aware procedures for governing IOMP data, investor reviews, inquiries, and certificate workflows.</p></div><span class="admin-status admin-status--approved">Staff only</span></header>
    <div class="staff-guide-callout"><div><i data-lucide="shield-alert" aria-hidden="true"></i></div><p><strong>Use the dedicated staff sign-in.</strong><span>Staff access begins at <a href="{{ route('staff.login') }}">{{ url('/staff/login') }}</a>. The public <strong>/login</strong> page is for investors and will not grant staff workspace access.</span></p></div>
    <div class="staff-guide-layout">
        <nav class="staff-guide-nav" aria-label="Staff guide sections"><strong>Procedures</strong><a href="#staff-access">Access and permissions</a><a href="#staff-data">District and opportunity data</a><a href="#staff-review">Workflow review</a><a href="#staff-investors">Investor KYC</a><a href="#staff-inquiries">Inquiries</a><a href="#staff-certificates">Certificates</a><a href="#staff-assistant">GIPA Assistant</a><a href="#staff-admin">Administration</a><a href="#staff-security">Security controls</a></nav>
        <article class="staff-guide-document">
            <section id="staff-access"><p class="guide-section__number">01 / Identity and scope</p><h2>Access and permissions</h2><ol><li>Open <a href="{{ route('staff.login') }}">/staff/login</a> and sign in with your assigned staff account.</li><li>Confirm the workspace name and your role in the sidebar footer.</li><li>Use only the menus and actions made available to your permissions.</li></ol><p>District Officers are additionally limited by active, dated district assignments. A missing menu or denied action normally means the role or district scope has not been assigned; contact a Super Administrator rather than using another account.</p></section>
            <section id="staff-data"><p class="guide-section__number">02 / Governed records</p><h2>Maintain districts and opportunities</h2><div class="guide-grid"><article><strong>District records</strong><span>Maintain identity, region, readiness, population, coordinates, and public profile information.</span></article><article><strong>Opportunity records</strong><span>Maintain project summary, sector, district, finance, contacts, media, and lifecycle status.</span></article><article><strong>Reference data</strong><span>Authorised users maintain sectors, sub-sectors, enterprise types, and investment structures.</span></article><article><strong>Data quality</strong><span>Verify coordinates, currency, amounts, ownership, and evidence before submission.</span></article></div><p>Published records feed the public directory, APIs, investment map, and investor matching. Treat every public field as operational data, not presentation copy.</p></section>
            <section id="staff-review"><p class="guide-section__number">03 / Four-eyes workflow</p><h2>Submit, review, and publish</h2><ol><li>Create or update a draft within your assigned scope.</li><li>Validate mandatory data and submit the record for review.</li><li>An authorised reviewer checks the evidence and records an approval or rejection reason.</li><li>Publish or activate only after approval and final data verification.</li></ol><div class="guide-note guide-note--warning"><strong>Separation of duties</strong><span>Do not bypass review controls or use another officer's credentials. Workflow events and record changes are audited.</span></div></section>
            <section id="staff-investors"><p class="guide-section__number">04 / Investor due diligence</p><h2>Review investor onboarding</h2><ol><li>Open <strong>Investments → Investor list</strong> and select a submitted case.</li><li>Confirm the profile type and required evidence checklist.</li><li>Inspect only evidence necessary for the assigned review.</li><li>Accept or reject each document with a clear, factual reason.</li><li>Request action when evidence is incomplete, or record the final case decision when requirements are met.</li></ol><p>Never retain investor evidence outside the platform. Decision notes are visible to the investor, so keep them specific, professional, and free of internal-only commentary.</p></section>
            <section id="staff-inquiries"><p class="guide-section__number">05 / Investor engagement</p><h2>Manage opportunity inquiries</h2><p>Use <strong>Investments → Inquiry list</strong> to review expressions of interest. Validate the project reference and contact information, assign responsibility where permitted, and record the current response status. Do not disclose another investor's details or internal review data.</p></section>
            <section id="staff-certificates"><p class="guide-section__number">06 / Controlled issuance</p><h2>Issue and manage certificates</h2><ol><li>Confirm that the investor, opportunity, and governing evidence are eligible.</li><li>Prepare the certificate from the approved platform snapshot.</li><li>Complete required verification and assignment steps.</li><li>Use suspension, reinstatement, or revocation only with an authorised reason.</li></ol><p>Certificate lifecycle actions are audited. Public verification displays a minimal current snapshot; private evidence, signatures, and internal decisions remain restricted.</p></section>
            <section id="staff-assistant"><p class="guide-section__number">07 / Assistant knowledge base</p><h2>Manage the GIPA Assistant</h2><p>The GIPA Assistant answers public and investor questions using a curated knowledge base plus live platform data. Staff with the <strong>assistant.knowledge.view</strong> permission can review the knowledge base under <strong>GIPA Assistant → Knowledge base</strong>; the <strong>assistant.knowledge.manage</strong> permission is required to create, edit, publish, or re-index documents.</p><ol><li>Open <a href="{{ route('staff.assistant.knowledge.index') }}">GIPA Assistant → Knowledge base</a> to see every document, its category, visibility, and indexing state.</li><li>Use <strong>Add document</strong> to author a title, category, summary, visibility, and body content. Saving indexes the document so the assistant can cite it.</li><li>Edit an existing document to correct content; re-indexing runs automatically when the body changes.</li><li>Set visibility to control whether an answer can surface on public pages or only inside the investor workspace.</li></ol><div class="guide-grid"><article><strong>Grounded and cited</strong><span>The assistant only answers from published knowledge and live counts, and attaches the sources it used.</span></article><article><strong>Queued full re-index</strong><span>Use <strong>Re-index all</strong> for a full rebuild. It runs in the background and the screen shows queued, running, completed, or failed status.</span></article><article><strong>Guardrails</strong><span>The assistant refuses out-of-scope requests, resists prompt-injection, and directs certificate checks to the official verification link.</span></article><article><strong>Retention</strong><span>Guest and investor conversations are pruned automatically after the configured retention period.</span></article></div><div class="guide-note guide-note--warning"><strong>Publish deliberately</strong><span>Only publish accurate, non-sensitive guidance. Anything you publish may be quoted verbatim to public visitors.</span></div></section>
            <section id="staff-admin"><p class="guide-section__number">08 / Administration</p><h2>Roles, users, and district assignments</h2><p>Super Administrators manage staff identities, roles, permissions, and district assignments under <strong>Users &amp; access</strong>. Grant the minimum access needed, add effective dates to assignments, and end access promptly when responsibilities change.</p></section>
            <section id="staff-security"><p class="guide-section__number">09 / Operational security</p><h2>Required controls</h2><ul><li>Use your own staff account and sign out from shared devices.</li><li>Do not export or retain private evidence outside an approved task.</li><li>Record reasons for decisions and avoid sensitive details in free-text notes.</li><li>Escalate suspicious uploads, account activity, or unexpected permission changes.</li><li>Keep queue workers, backups, signing keys, TLS, and monitoring operational in production.</li></ul></section>
        </article>
    </div>
</x-admin-layout>