<x-admin-layout :title="$opportunity->title">
    <nav class="admin-breadcrumb"><a href="{{ route('staff.opportunities.index') }}">Opportunities</a><span>/</span><span>{{ str($opportunity->title)->limit(52) }}</span></nav>
    <div class="review-heading"><div><span class="admin-status admin-status--{{ $opportunity->workflow_status }}">{{ str($opportunity->workflow_status)->replace('_',' ')->title() }}</span><h1>{{ $opportunity->title }}</h1><p>{{ $opportunity->district->name }}, {{ $opportunity->district->region->name }} · {{ $opportunity->sector->name }}</p></div><dl><div><dt>Version</dt><dd>{{ $opportunity->version }}</dd></div><div><dt>Reviewer</dt><dd>{{ $opportunity->reviewer?->name ?? 'Unassigned' }}</dd></div><div><dt>SLA due</dt><dd @class(['is-overdue'=>$opportunity->sla_due_at?->isPast()])>{{ $opportunity->sla_due_at?->format('j M Y, H:i') ?? 'Not active' }}</dd></div></dl></div>
    <div class="review-layout"><article class="review-content"><section><h2>Opportunity record</h2><p>{{ $opportunity->overview }}</p><div class="review-facts"><div><span>Enterprise type</span><strong>{{ $opportunity->enterpriseType->name }}</strong></div><div><span>Investment</span><strong>{{ $opportunity->financial?->amount ? $opportunity->financial->currency.' '.number_format((float)$opportunity->financial->amount) : 'On request' }}</strong></div><div><span>Structure</span><strong>{{ $opportunity->financial?->investmentStructure?->name ?? 'Not specified' }}</strong></div><div><span>Documents</span><strong>{{ $opportunity->media->count() }}</strong></div></div></section>@foreach(['rationale'=>'Rationale','objectives'=>'Objectives','success_factors'=>'Success factors','competitive_advantages'=>'Competitive advantages'] as $field=>$label)@if($opportunity->{$field})<section><h2>{{ $label }}</h2><p>{{ $opportunity->{$field} }}</p></section>@endif @endforeach<section><h2>Workflow history</h2><ol class="workflow-timeline">@forelse($opportunity->workflowEvents as $event)<li><i aria-hidden="true"></i><div><strong>{{ str($event->action)->replace('_',' ')->title() }}</strong><span>{{ str($event->from_status)->replace('_',' ')->title() }} → {{ str($event->to_status)->replace('_',' ')->title() }}</span><small>{{ $event->actor?->name ?? 'System' }} · {{ $event->occurred_at->format('j M Y, H:i') }}</small>@if($event->reason)<p>{{ $event->reason }}</p>@endif</div></li>@empty<li class="timeline-empty">No workflow actions recorded.</li>@endforelse</ol></section></article>
        <aside class="action-panel"><p class="admin-kicker">Available action</p><h2>Move this record</h2><p>Actions are recorded permanently with actor, time and decision context.</p>
            @if($opportunity->workflow_status === 'draft' && auth()->user()->can('opportunities.submit'))<form method="post" action="{{ route('staff.opportunities.transition', [$opportunity,'submit']) }}">@csrf<label class="field"><span>Assign reviewer</span><select name="reviewer" required><option value="">Select reviewer</option>@foreach($reviewers as $reviewer)<option value="{{ $reviewer->uuid }}">{{ $reviewer->name }}</option>@endforeach</select></label><button class="button button--gold" type="submit">Submit for approval</button></form>@endif
            @if($opportunity->workflow_status === 'pending_approval' && auth()->user()->can('opportunities.review'))<form method="post" action="{{ route('staff.opportunities.transition', [$opportunity,'approve']) }}">@csrf<label class="field"><span>Decision note</span><textarea name="reason" rows="3"></textarea></label><button class="button button--approve" type="submit">Approve opportunity</button></form><form method="post" action="{{ route('staff.opportunities.transition', [$opportunity,'reject']) }}">@csrf<label class="field"><span>Required changes</span><textarea name="reason" rows="3" required></textarea></label><button class="button button--danger-outline" type="submit">Reject for changes</button></form>@endif
            @if($opportunity->workflow_status === 'pending_approval' && auth()->user()->can('opportunities.reassign'))<form method="post" action="{{ route('staff.opportunities.transition', [$opportunity,'reassign']) }}">@csrf<label class="field"><span>Reassign reviewer</span><select name="reviewer" required><option value="">Select reviewer</option>@foreach($reviewers as $reviewer)<option value="{{ $reviewer->uuid }}">{{ $reviewer->name }}</option>@endforeach</select></label><label class="field"><span>Reason</span><textarea name="reason" rows="2"></textarea></label><button class="button button--outline" type="submit">Reassign</button></form>@endif
            @if($opportunity->workflow_status === 'approved' && auth()->user()->can('opportunities.lifecycle'))<form method="post" action="{{ route('staff.opportunities.transition', [$opportunity,'activate']) }}">@csrf<button class="button button--approve" type="submit">Activate and publish</button></form>@endif
            @if($opportunity->workflow_status === 'active' && auth()->user()->can('opportunities.lifecycle'))<form method="post" action="{{ route('staff.opportunities.transition', [$opportunity,'complete']) }}">@csrf<button class="button button--approve" type="submit">Mark completed</button></form>@endif
            @if(in_array($opportunity->workflow_status,['approved','active']) && auth()->user()->can('opportunities.lifecycle'))<form method="post" action="{{ route('staff.opportunities.transition', [$opportunity,'cancel']) }}">@csrf<label class="field"><span>Cancellation reason</span><textarea name="reason" rows="3" required></textarea></label><button class="button button--danger-outline" type="submit">Cancel opportunity</button></form>@endif
            @unless(in_array($opportunity->workflow_status,['draft','pending_approval','approved','active']) || auth()->user()->can('opportunities.lifecycle'))<div class="no-action">No workflow action is available for your role.</div>@endunless
        </aside>
    </div>
</x-admin-layout>