<x-admin-layout title="Dashboard">
    <div class="admin-page-heading"><div><p class="admin-kicker">Operational overview</p><h1>Investment pipeline</h1><p>Monitor approvals, district publication and investor response workload.</p></div><a class="button button--gold" href="{{ route('staff.opportunities.index') }}">Open review queue</a></div>
    <section class="metric-widget-grid" aria-label="Platform indicators">
        <x-metric-widget label="Investable portfolio" :value="number_format($metrics['investable_opportunities'])" :note="number_format($metrics['opportunities']).' total opportunities'" icon="briefcase-business" tone="green" />
        <x-metric-widget label="Verified investors" :value="number_format($metrics['verified_investors'])" :note="number_format($metrics['onboarding_review']).' currently in review'" icon="badge-check" tone="blue" />
        <x-metric-widget label="National coverage" :value="number_format($metrics['districts'])" :note="number_format($metrics['districts_under_review']).' district profiles in review'" icon="map-pinned" tone="gold" />
        <x-metric-widget label="Attention required" :value="number_format($metrics['sla_breaches'])" :note="number_format($metrics['open_inquiries']).' open investor inquiries'" icon="triangle-alert" tone="red" />
    </section>
    <section class="dashboard-chart-grid" aria-label="Decision analytics">
        <x-chart-panel title="Opportunity portfolio" description="Lifecycle composition across the national pipeline." type="doughnut" :labels="$charts['opportunity_status']['labels']" :datasets="[['label'=>'Opportunities','data'=>$charts['opportunity_status']['values']]]" :summary="'Opportunity lifecycle figures: '.collect($charts['opportunity_status']['labels'])->zip($charts['opportunity_status']['values'])->map(fn($item) => $item[0].' '.$item[1])->join(', ')" />
        <x-chart-panel title="Investor onboarding" description="Current KYC and decision workload by stage." type="bar" :labels="$charts['onboarding_status']['labels']" :datasets="[['label'=>'Cases','data'=>$charts['onboarding_status']['values']]]" :summary="'Investor onboarding figures: '.collect($charts['onboarding_status']['labels'])->zip($charts['onboarding_status']['values'])->map(fn($item) => $item[0].' '.$item[1])->join(', ')" />
        <x-chart-panel title="Application intake" description="Investor submissions received over the last six months." type="line" :labels="$charts['onboarding_months']['labels']" :datasets="[['label'=>'Submitted cases','data'=>$charts['onboarding_months']['values']]]" :summary="'Monthly onboarding submissions: '.collect($charts['onboarding_months']['labels'])->zip($charts['onboarding_months']['values'])->map(fn($item) => $item[0].' '.$item[1])->join(', ')" wide />
    </section>
    <section class="admin-section"><div class="admin-section__heading"><div><h2>Approval queue</h2><p>Items closest to their service deadline appear first.</p></div><a href="{{ route('staff.opportunities.index', ['status'=>'pending_approval']) }}">View all</a></div>
        <div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Opportunity</th><th>District</th><th>Reviewer</th><th>SLA</th><th></th></tr></thead><tbody>@forelse($reviewQueue as $item)<tr><td><strong>{{ $item->title }}</strong><small>Pending approval</small></td><td>{{ $item->district->name }}</td><td>{{ $item->reviewer?->name ?? 'Unassigned' }}</td><td @class(['is-overdue'=>$item->sla_due_at?->isPast()])>{{ $item->sla_due_at?->diffForHumans() ?? 'Not set' }}</td><td><a href="{{ route('staff.opportunities.show', $item) }}">Review</a></td></tr>@empty<tr><td colspan="5" class="table-empty">No opportunities are awaiting approval.</td></tr>@endforelse</tbody></table></div>
    </section>
</x-admin-layout>