<x-admin-layout :title="str($page)->replace('-', ' ')->title()">
    @if($page === 'opportunities')
        <div class="admin-page-heading"><div><p class="admin-kicker">Opportunity intelligence</p><h1>Opportunities overview</h1><p>Navigate the geographic registry, investment pipeline and governed reference data.</p></div></div>
        <section class="metric-widget-grid"><x-metric-widget label="Regions" :value="number_format($regions)" note="National coverage" icon="map" tone="green" /><x-metric-widget label="Districts" :value="number_format($districts)" note="Registry records" icon="landmark" tone="blue" /><x-metric-widget label="Opportunities" :value="number_format($opportunities)" note="Total portfolio" icon="layers-3" tone="gold" /><x-metric-widget label="Active" :value="number_format($active)" note="Published investments" icon="activity" tone="red" /></section>
        <section class="dashboard-chart-grid" aria-label="Opportunity coverage analytics">
            <x-chart-panel title="Portfolio and geographic coverage" description="Comparison of national coverage and the current opportunity pipeline." type="bar" :labels="$opportunityCharts['coverage']['labels']" :datasets="[['label'=>'Records','data'=>$opportunityCharts['coverage']['values']]]" :summary="'Coverage figures: '.collect($opportunityCharts['coverage']['labels'])->zip($opportunityCharts['coverage']['values'])->map(fn($item) => $item[0].' '.$item[1])->join(', ')" />
            <x-chart-panel title="Active portfolio share" description="Active opportunities compared with records in all other lifecycle stages." type="pie" :labels="$opportunityCharts['portfolio']['labels']" :datasets="[['label'=>'Opportunities','data'=>$opportunityCharts['portfolio']['values']]]" :summary="'Portfolio share: '.collect($opportunityCharts['portfolio']['labels'])->zip($opportunityCharts['portfolio']['values'])->map(fn($item) => $item[0].' '.$item[1])->join(', ')" />
        </section>
    @elseif($page === 'regions')
        <div class="admin-page-heading"><div><p class="admin-kicker">Geographic registry</p><h1>Region list</h1><p>Coverage and published district profiles across Ghana's administrative regions.</p></div></div>
        <div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Region</th><th>Code</th><th>Capital</th><th>Districts</th><th>Published</th></tr></thead><tbody>@foreach($regions as $region)<tr><td><strong>{{ $region->name }}</strong></td><td>{{ $region->code }}</td><td>{{ $region->capital ?? 'Not recorded' }}</td><td>{{ $region->districts_count }}</td><td>{{ $region->published_districts_count }}</td></tr>@endforeach</tbody></table></div>
    @elseif($page === 'investments')
        <div class="admin-page-heading"><div><p class="admin-kicker">Investor services</p><h1>Investments overview</h1><p>Track investor participation, onboarding outcomes and opportunity inquiries.</p></div></div>
        <section class="metric-widget-grid"><x-metric-widget label="Investors" :value="number_format($investors)" note="Registered profiles" icon="users-round" tone="green" /><x-metric-widget label="Applications" :value="number_format($applications)" note="Onboarding cases" icon="clipboard-list" tone="blue" /><x-metric-widget label="Approved" :value="number_format($approved)" note="Verified investors" icon="badge-check" tone="gold" /><x-metric-widget label="Inquiries" :value="number_format($inquiries)" note="Opportunity interest" icon="messages-square" tone="red" /></section>
    @elseif($page === 'inquiries')
        <div class="admin-page-heading"><div><p class="admin-kicker">Investor engagement</p><h1>Inquiry list</h1><p>Review investment interest and follow-up ownership.</p></div></div>
        <div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Contact</th><th>Opportunity</th><th>Subject</th><th>Status</th><th>Assigned</th></tr></thead><tbody>@forelse($inquiries as $inquiry)<tr><td><strong>{{ $inquiry->name }}</strong><small>{{ $inquiry->email }}</small></td><td>{{ $inquiry->opportunity?->title ?? 'Unavailable' }}</td><td>{{ $inquiry->subject }}</td><td><span class="admin-status">{{ str($inquiry->status)->title() }}</span></td><td>{{ $inquiry->assignee?->name ?? 'Unassigned' }}</td></tr>@empty<tr><td colspan="5" class="table-empty">No inquiries have been received.</td></tr>@endforelse</tbody></table></div><div class="admin-pagination">{{ $inquiries->links() }}</div>
    @elseif(in_array($page, ['notifications', 'notification-list']))
        <div class="admin-page-heading"><div><p class="admin-kicker">Workspace activity</p><h1>{{ $page === 'notifications' ? 'Notifications overview' : 'Notification list' }}</h1><p>{{ number_format($unread) }} unread notifications require attention.</p></div></div>
        @if($page === 'notifications')<section class="metric-widget-grid"><x-metric-widget label="Unread" :value="number_format($unread)" note="Needs attention" icon="bell-ring" tone="gold" /><x-metric-widget label="Total received" :value="number_format($notifications->total())" note="Your activity feed" icon="inbox" tone="blue" /></section>@else<div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Notification</th><th>Received</th><th>Status</th></tr></thead><tbody>@forelse($notifications as $notification)<tr><td><strong>{{ $notification->data['message'] ?? class_basename($notification->type) }}</strong></td><td>{{ $notification->created_at->diffForHumans() }}</td><td>{{ $notification->read_at ? 'Read' : 'Unread' }}</td></tr>@empty<tr><td colspan="3" class="table-empty">No notifications yet.</td></tr>@endforelse</tbody></table></div>@endif
    @elseif($page === 'users')
        <div class="admin-page-heading"><div><p class="admin-kicker">Identity and access</p><h1>Users overview</h1><p>Review staff access, role coverage and the permission catalogue.</p></div></div><section class="metric-widget-grid"><x-metric-widget label="Staff" :value="number_format($staff->count())" note="Workspace accounts" icon="users" tone="green" /><x-metric-widget label="Roles" :value="number_format($roles->count())" note="Access profiles" icon="shield" tone="blue" /><x-metric-widget label="Permissions" :value="number_format($permissions->count())" note="Governed capabilities" icon="key-round" tone="gold" /></section>
    @elseif($page === 'staff')
        <div class="admin-page-heading"><div><p class="admin-kicker">Identity and access</p><h1>Staff list</h1><p>Authorized workspace accounts and assigned roles.</p></div></div><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Staff member</th><th>Email</th><th>Role</th><th>Status</th></tr></thead><tbody>@foreach($staff as $user)<tr><td><strong>{{ $user->name }}</strong></td><td>{{ $user->email }}</td><td>{{ $user->roles->pluck('name')->join(', ') }}</td><td>{{ str($user->status)->title() }}</td></tr>@endforeach</tbody></table></div>
    @elseif($page === 'roles')
        <div class="admin-page-heading"><div><p class="admin-kicker">Identity and access</p><h1>Roles</h1><p>Access profiles and their current coverage.</p></div></div><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Role</th><th>Users</th><th>Permissions</th></tr></thead><tbody>@foreach($roles as $role)<tr><td><strong>{{ $role->name }}</strong></td><td>{{ $role->users_count }}</td><td>{{ $role->permissions_count }}</td></tr>@endforeach</tbody></table></div>
    @else
        <div class="admin-page-heading"><div><p class="admin-kicker">Identity and access</p><h1>Permissions</h1><p>Capabilities granted through managed roles.</p></div></div><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Permission</th><th>Assigned roles</th></tr></thead><tbody>@foreach($permissions as $permission)<tr><td><strong>{{ $permission->name }}</strong></td><td>{{ $permission->roles->pluck('name')->join(', ') ?: 'Not assigned' }}</td></tr>@endforeach</tbody></table></div>
    @endif
</x-admin-layout>