<x-admin-layout :title="$case->reference">
    <nav class="admin-breadcrumb">
        <a href="{{ route('staff.investors.index') }}">Investor onboarding</a>
        <span>/</span>
        <span>{{ $case->reference }}</span>
    </nav>
    <div class="review-heading"><div>
    <span class="admin-status admin-status--{{ $case->status }}">{{ str($case->status)->replace('_',' ')->title() }}</span>
    <h1>{{ $case->profile->display_name }}</h1>
    <p>{{ $case->profile->user->email }} · {{ str($case->profile->profile_type)->replace('_',' ')->title() }}</p></div>
    <dl><div><dt>Version</dt><dd>{{ $case->version }}</dd></div><div><dt>Reviewer</dt><dd>{{ $case->assignee?->name ?? 'Unassigned' }}</dd></div><div><dt>SLA due</dt><dd @class(['is-overdue' => $case->sla_due_at?->isPast()])>{{ $case->sla_due_at?->format('j M Y, H:i') ?? 'Not active' }}</dd></div></dl></div>
    <div class="review-layout"><article class="review-content"><section><h2>Investor record</h2><div class="review-facts"><div><span>Country</span><strong>{{ $case->profile->country_code }}</strong></div><div><span>Nationality</span><strong>{{ $case->profile->nationality_country_code ?? 'Not supplied' }}</strong></div><div><span>Organization</span><strong>{{ $case->profile->user->organization ?: 'Individual' }}</strong></div><div><span>Phone</span><strong>{{ $case->profile->user->phone ?: 'Not supplied' }}</strong></div></div></section>
        <section><h2>KYC evidence</h2><div class="evidence-list evidence-list--review">@forelse($case->documents as $document)<article><div><strong>{{ $document->type->name }}</strong><small>SHA-256 {{ str($document->checksum_sha256)->limit(18) }} · Scan {{ str($document->malware_scan_status)->title() }}</small>@if($document->expires_at)<small>Expires {{ $document->expires_at->format('j M Y') }}</small>@endif @if($document->rejection_reason)<p>{{ $document->rejection_reason }}</p>@endif</div><span class="admin-status admin-status--{{ $document->status }}">{{ str($document->status)->title() }}</span><a href="{{ route('investor.documents.download', $document) }}">Inspect</a>@can('investors.compliance.manage')@if($document->status === 'quarantined')<form method="post" action="{{ route('staff.investor-documents.decision', [$document,'accept']) }}">@csrf<button type="submit">Record clean scan & accept</button></form><form method="post" action="{{ route('staff.investor-documents.decision', [$document,'reject']) }}">@csrf<input name="reason" maxlength="2000" placeholder="Rejection reason" required><button type="submit">Reject</button></form>@endif @endcan</article>@empty<p class="table-empty">No evidence submitted.</p>@endforelse</div></section>
        <section><h2>Workflow history</h2><ol class="workflow-timeline">@foreach($case->events as $event)<li><i aria-hidden="true"></i><div><strong>{{ str($event->action)->replace('_',' ')->title() }}</strong><span>{{ str($event->from_status)->replace('_',' ')->title() }} → {{ str($event->to_status)->replace('_',' ')->title() }}</span><small>{{ $event->actor?->name ?? 'System' }} · {{ $event->occurred_at->format('j M Y, H:i') }}</small>@if($event->reason)<p>{{ $event->reason }}</p>@endif</div></li>@endforeach</ol></section></article>
        <aside class="action-panel"><p class="admin-kicker">Review decision</p><h2>Move this case</h2><p>Every action is authorized, versioned, audited, and retained.</p>@can('investors.review')
            @if($case->status === 'submitted')<form method="post" action="{{ route('staff.investors.transition', [$case,'start-review']) }}">@csrf<button class="button button--gold" type="submit">Accept assignment</button></form>@endif
            @if($case->status === 'under_review')<form method="post" action="{{ route('staff.investors.transition', [$case,'approve']) }}">@csrf<label class="field"><span>Decision note</span><textarea name="reason" rows="3"></textarea></label><button class="button button--approve" type="submit">Approve onboarding</button></form><form method="post" action="{{ route('staff.investors.transition', [$case,'request-changes']) }}">@csrf<label class="field"><span>Required changes</span><textarea name="reason" rows="3" required></textarea></label><button class="button button--outline" type="submit">Request changes</button></form><form method="post" action="{{ route('staff.investors.transition', [$case,'reject']) }}">@csrf<label class="field"><span>Rejection reason</span><textarea name="reason" rows="3" required></textarea></label><button class="button button--danger-outline" type="submit">Reject application</button></form>@endif
        @endcan @unless(in_array($case->status, ['submitted','under_review']))<div class="no-action">No workflow action is available in this state.</div>@endunless</aside>
    </div>
</x-admin-layout>