<x-admin-layout :title="$certificate->certificate_number">
    <nav class="admin-breadcrumb" aria-label="Breadcrumb"><a href="{{ route('staff.certificates.index') }}">Certificates</a><span>/</span><span>{{ $certificate->certificate_number }}</span></nav>
    <div class="review-heading"><div><span class="admin-status admin-status--{{ $certificate->status }}">{{ str($certificate->status)->title() }}</span><h1>{{ $certificate->holder_name_snapshot }}</h1><p>{{ $certificate->certificate_number }} · {{ $certificate->type->name }}</p></div><dl><div><dt>Integrity</dt><dd>{{ str($integrityResult)->replace('_',' ')->title() }}</dd></div><div><dt>Version</dt><dd>{{ $certificate->version }}</dd></div><div><dt>District</dt><dd>{{ $certificate->district->name }}</dd></div></dl></div>
    <div class="review-layout"><article class="review-content">
        <section><h2>Certificate snapshot</h2><div class="review-facts"><div><span>Organization</span><strong>{{ $certificate->organization_name_snapshot ?: 'Not specified' }}</strong></div><div><span>Project</span><strong>{{ $certificate->project_name_snapshot ?: 'Not linked' }}</strong></div><div><span>Issued</span><strong>{{ $certificate->issued_at?->format('j M Y, H:i') ?? 'Draft' }}</strong></div><div><span>Expires</span><strong>{{ $certificate->expires_at?->format('j M Y') ?? 'No fixed expiry' }}</strong></div><div><span>Issuer</span><strong>{{ $certificate->issuer?->name ?? 'Not issued' }}</strong></div><div><span>Signing key</span><strong>{{ $certificate->signing_key_id ?? 'Not signed' }}</strong></div></div>@if($certificate->public_token)<p class="certificate-link"><strong>Public verification</strong><a href="{{ route('certificates.verify', $certificate->public_token) }}" target="_blank" rel="noopener">{{ route('certificates.verify', $certificate->public_token) }}</a></p>@endif @if($certificate->artifact_status === 'ready')<div class="artifact-actions"><a class="button button--outline" href="{{ route('staff.certificates.artifact', [$certificate,'pdf']) }}">Download certificate PDF</a><a class="button button--outline" href="{{ route('staff.certificates.artifact', [$certificate,'qr']) }}">Download QR</a></div>@elseif($certificate->status !== 'draft')<p class="muted-copy">Certificate artifacts: {{ str($certificate->artifact_status)->title() }}.</p>@endif</section>
        <section><h2>Field verification history</h2><div class="evidence-list evidence-list--review">@forelse($certificate->verifications as $verification)<article><div><strong>{{ $verification->reference }}</strong><small>{{ $verification->officer->name }} · {{ $verification->created_at->format('j M Y, H:i') }}</small><small>System: {{ str($verification->system_result)->replace('_',' ')->title() }} · Officer: {{ str($verification->officer_decision)->title() }}</small>@if($verification->notes)<p>{{ $verification->notes }}</p>@endif</div><span class="admin-status admin-status--{{ $verification->officer_decision }}">{{ $verification->officer_decision }}</span>@if($verification->hasMedia($verification::EVIDENCE_COLLECTION)) @can('viewEvidence', $verification)<a href="{{ route('staff.certificates.evidence', $verification) }}">Evidence</a>@endcan @endif</article>@empty<p class="table-empty">No field verification has been recorded.</p>@endforelse</div></section>
        <section><h2>Lifecycle history</h2><ol class="workflow-timeline">@forelse($certificate->lifecycleEvents as $event)<li><i aria-hidden="true"></i><div><strong>{{ str($event->action)->title() }}</strong><span>{{ str($event->from_status)->title() }} → {{ str($event->to_status)->title() }}</span><small>{{ $event->actor?->name ?? 'System' }} · {{ $event->occurred_at->format('j M Y, H:i') }}</small>@if($event->reason)<p>{{ $event->reason }}</p>@endif</div></li>@empty<li><i aria-hidden="true"></i><div><strong>Draft prepared</strong><small>Awaiting controlled issuance</small></div></li>@endforelse</ol></section>
    </article><aside class="action-panel"><p class="admin-kicker">Controlled action</p><h2>{{ $certificate->status === 'draft' ? 'Issue certificate' : 'Field decision' }}</h2>
        @if($certificate->status === 'draft') @can('certificates.issue')<p>Issuance signs and freezes the certificate snapshot.</p><form method="post" action="{{ route('staff.certificates.action', [$certificate,'issue']) }}">@csrf<button class="button button--gold" type="submit">Sign and issue</button></form>@endcan
        @else @can('verify', $certificate)<p>Record the physical inspection separately from the registry result.</p><form method="post" enctype="multipart/form-data" action="{{ route('staff.certificates.verify', $certificate) }}">@csrf<input type="hidden" name="idempotency_key" value="{{ Str::uuid() }}"><label class="field"><span>Officer decision</span><select name="officer_decision" required><option value="valid">Valid</option><option value="suspicious">Suspicious</option><option value="invalid">Invalid</option></select></label><label class="field"><span>Inspection note</span><textarea name="notes" rows="4" maxlength="2000"></textarea></label><div class="field-coordinate-grid"><label class="field"><span>Latitude</span><input type="number" step="0.0000001" min="-90" max="90" name="latitude"></label><label class="field"><span>Longitude</span><input type="number" step="0.0000001" min="-180" max="180" name="longitude"></label></div><label class="field"><span>Private evidence</span><input type="file" name="evidence" accept="image/jpeg,image/png,image/webp,application/pdf"><small>Maximum 10 MB. Security scan remains pending.</small></label><button class="button button--gold" type="submit">Record verification</button></form>@endcan
        @can('certificates.suspend') @if($certificate->status === 'active')<form method="post" action="{{ route('staff.certificates.action', [$certificate,'suspend']) }}">@csrf<label class="field"><span>Suspension reason</span><textarea name="reason" required maxlength="2000"></textarea></label><button class="button button--outline" type="submit">Suspend</button></form>@elseif($certificate->status === 'suspended')<form method="post" action="{{ route('staff.certificates.action', [$certificate,'reinstate']) }}">@csrf<label class="field"><span>Reinstatement reason</span><textarea name="reason" required maxlength="2000"></textarea></label><button class="button button--approve" type="submit">Reinstate</button></form>@endif @endcan
        @can('certificates.revoke') @if(in_array($certificate->status, ['active','suspended']))<form method="post" action="{{ route('staff.certificates.action', [$certificate,'revoke']) }}">@csrf<label class="field"><span>Revocation reason</span><textarea name="reason" required maxlength="2000"></textarea></label><button class="button button--danger-outline" type="submit">Revoke</button></form>@endif @endcan @endif
    </aside></div>
</x-admin-layout>