name: Sync Main and UAT to MCC Organization

on:
  push:
    branches:
      - main
      - uat

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sync branch to organization
        env:
          ORG_TOKEN: ${{ secrets.MCC_ORG_GIPA_REPO_TOKEN }}
        run: |
          git remote add organization \
            "https://x-access-token:${ORG_TOKEN}@github.com/Mobile-Content-Ltd/gipa_demo.git"

          git push organization \
            "refs/heads/${GITHUB_REF_NAME}:refs/heads/${GITHUB_REF_NAME}" \
            --force

            